# FIX Dublicated, Hexedecimal and string charaters

In [2]:
import os
from tqdm import tqdm
import pandas as pd
import numpy as np
import math
import warnings
warnings.filterwarnings("ignore")

C:\Users\kahra\AppData\Local\Temp\ipykernel_25232\3422249959.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
strs={"http_connection": {'Close': 1, 'Keep-Alive': 2, 'close': 3, 'keep-alive': 4},
"http_request_method": {'DELETE': 1, 'GET': 2, 'M-SEARCH': 3, 'NOTIFY': 4, 'POST': 5, 'PUT': 6},
"http_request_uri_path": {'/agent/upgrade': 1, '/dst': 2, '/queue/getmessage': 3,
                        '/router/firmware/query.aspx': 4, '/scale/register': 5, '/scale/validate': 6},
"http_response_code_desc": {'Continue': 1, 'Not Found': 2, 'OK': 3, 'Unauthorized': 4},
 "http_response_phrase": {'Continue': 1, 'Not Found': 2, 'OK': 3, 'Unauthorized': 4},
"dns_srv_proto": {'_dhnap': 1, '_dhnap,_http': 2, '_hap': 3, '_http': 4, '_http,_dhnap': 5, '_http,_http': 6},
"tcp_flags_str": {'·······AP··F': 1, '·······AP···': 2, '·······A·R··': 3, '·······A··S·': 4,
                '·······A···F': 5, '·······A····': 6, '·········R··': 7,  '··········S·': 8},
"_ws_col_Protocol": {'EAPOL':1,'DHCP':2,'DNS':3,'TCP':4,'HTTP':5,'ICMP':6,'MDNS':7,'IGMPv3':8,'SSDP':9,'NTP':10,'HTTP/XML':11,'UDP':12,'SSLv2':13,'TLSv1':14,
'ADwin Config':15,'TLSv1.2':16,'ICMPv6':17,'HTTP/JSON':18,'XID':19,'TFTP':20,'NXP 802.15.4 SNIFFER':21,'IGMPv2':22,'A21':23,'STUN':24,'Gearman':25,
'?KNXnet/IP':26,'UDPENCAP':27,'ESP':28,'SSL':29,'NBNS':30,'SIP':31,'BROWSER':32,'SABP':33,'ISAKMP':34,'CLASSIC-STUN':35,'Omni-Path':36,'XMPP/XML':37,
'ULP':38,'TFPoverTCP':39,'AX4000':40,'MIH':41,'DHCPv6':42,'TDLS':43,'RTMP':44,'TCPCL':45,'IPA':46,'GQUIC':47,'0x86dd':48,'DB-LSP-DISC':49,'SSLv3':50,
'LLMNR':51,'FB_ZERO':52,'OCSP':53,'IPv4':54,'STP':55,'SSH':56,'TLSv1.1':57,'KINK':58,'MANOLITO':59,'PKTC':60,'TELNET':61,'RTSP':62,'HCrt':63,'MPTCP':64,
'S101':65,'IRC':66,'AJP13':67,'PMPROXY':68,'PNIO':69,'AMS':70,'ECATF':71,'LLC':72,'TZSP':73,'RSIP':74,'SSHv2':75,'DIAMETER':76,'BFDControl':77,'ASAP':78
,'DISTCC':79,'DISTCC':79,'LISP':80,'WOW':81,'DTLSv1.0':82,'SNMP':83,'SMB2':84,'SMB':85,'NBSS':86,'UDT':87,'HiQnet':88,'POWERLINK/UDP':89
,'RTP':90,'WebSocket':91,'NAT-PMP':92,'RTCP':93,'Syslog':94,'Portmap':95,'OpenVPN':96,'BJNP':97,'RIPv1':98,'MAC-Telnet':99,'ECHO':100,'ASF':101
,'DAYTIME':102,'SRVLOC':103,'KRB4':104,'CAPWAP-Control':105,'XDMCP':106,'Chargen':107,'RADIUS':108,'L2TP':109,'DCERPC':110,'KPASSWD':111,'H264':112
,'FTP':113,'FTP-DATA':114,'ENIP':115,'RIPv2':116,'ICP':117,"BACnet-APDU":118,"IAX2":119,"RX":120,"HTTP2":121,"SIP/SDP":122,"TIME":123,
"Elasticsearch":124,"RSL":125,"TPCP":126,"IPv6":127,"ARP":128}}


dubs=["tls.handshake.sig_hash_alg",
"dhcp.hw.type",
"ip.dsfield",
"ip.flags",
"ipv6.opt.type",
"ipv6.opt.type.rest",
"stun.att.family",
"stun.att.ipv4-xord",
"stun.att.port-xord",
"tcp.segment",
"arp.duplicate-address-detected",
"arp.duplicate-address-frame",
"dns.srv.port",
"dns.srv.priority",
"dns.srv.weight",
"eth.addr.oui",
"eth.ig",
"eth.lg",
"ip.checksum.status",
"ip.dsfield.dscp",
"ip.dsfield.ecn",
"ip.flags.df",
"ip.flags.mf",
'arp.seconds-since-duplicate-address-frame',
'ip.len',
'ip.id',
"ip.flags.rb",
"ip.frag_offset",
"ip.hdr_len",
"ip.proto",
"ip.ttl",
"ip.version",
"ipv6.opt",
"ipv6.opt.length",
"ipv6.opt.type.action",
"ipv6.opt.type.change",
"stun.att.padding",
"stun.att.port",
"stun.att.reserved",
"tcp.analysis.duplicate_ack",
"tcp.port",
"tls.record.length",
"udp.port",
"ip.dst",
"ip.src",
"ip.src_host",
"stun.att.ipv4",
"dhcp.hw.mac_addr"]


#'arp.seconds-since-duplicate-address-frame',
 #'ip.len',
 #, bol hex
 #, 32

hexvalues=["stun.cookie",
"stun.id",
"stun.value",
"tcp.options",
"tcp.options.mss",
"tcp.options.sack",
"tcp.options.wscale",
"ntp.refid",
"stun.att.username",
"arp.proto.type",
"dhcp.flags",
"dhcp.flags.reserved",
"dhcp.id",
"dns.flags",
"dns.id",
"eth.fcs",
"eth.type",
"icmp.checksum",
"icmpv6.checksum",
"igmp.checksum",
"igmp.type",
"ip.id",
"ipv6.flow",
"ipv6.tclass",
"ntp.flags",
"stun.att.crc32",
"stun.att.transp",
"stun.type",
"stun.type.class",
"stun.type.method",
"stun.type.method-assignment",
"tcp.checksum",
"tcp.flags",
"tls.handshake.server_curve_type",
"tls.handshake.server_named_curve",
"tls.handshake.version",
"udp.checksum",
"dhcp.hw.type",
"ipv6.opt.type","tls.handshake.sig_hash_alg",
"ip.dsfield",
"ip.flags",
"stun.att.family",
"stun.att.ipv4-xord",
"stun.att.port-xord",
"ipv6.opt.type.rest"]


In [4]:
def find_the_way(path,file_format,con=""):
    files_add = []
    # r=root, d=directories, f = files
    for r, d, f in os.walk(path):
        for file in f:
            if file_format in file:
                if con in file:
                    files_add.append(os.path.join(r, file))  
            
    return files_add
path="pcaps"

def folder(f_name): #this function creates a folder named "attacks" in the program directory.
    try:
        if not os.path.exists(f_name):
            os.makedirs(f_name)
    except OSError:
        print ("Tthe folder could not be created!")


In [5]:
#the list of remaining features after string features have been eliminated, 

selected_cols=["dns.time",
"http.time",
"icmp.data_time_relative",
"icmp.resptime",
"stun.time",
"tcp.ack",
"tcp.ack_raw",
"tcp.analysis.ack_rtt",
"tcp.analysis.initial_rtt",
"tcp.analysis.rto",
"tcp.nxtseq",
"tcp.options.timestamp.tsecr",
"tcp.options.timestamp.tsval",
"tcp.seq",
"tcp.seq_raw",
"tcp.time_delta",
"tcp.time_relative",
"udp.time_delta",
"udp.time_relative",
"arp.hw.size",
"arp.hw.type",
"arp.isannouncement",
"arp.isgratuitous",
"arp.isprobe",
"arp.opcode",
"arp.proto.size",
"arp.seconds-since-duplicate-address-frame",
"dhcp.flags.bc",
"dhcp.hops",
"dhcp.hw.addr_padding",
"dhcp.hw.len",
"dhcp.option.dhcp",
"dhcp.option.dhcp_max_message_size",
"dhcp.option.end",
"dhcp.option.interface_mtu",
"dhcp.option.ip_address_lease_time",
"dhcp.option.padding",
"dhcp.option.rebinding_time_value",
"dhcp.option.renewal_time_value",
"dhcp.secs",
"dhcp.type",
"dns.count.add_rr",
"dns.count.answers",
"dns.count.auth_rr",
"dns.count.queries",
"dns.extraneous",
"dns.extraneous.data",
"dns.extraneous.length",
"dns.flags.authenticated",
"dns.flags.authoritative",
"dns.flags.checkdisable",
"dns.flags.opcode",
"dns.flags.rcode",
"dns.flags.recavail",
"dns.flags.recdesired",
"dns.flags.response",
"dns.flags.truncated",
"dns.flags.z",
"dns.response_to",
"dns.retransmission",
"dns.retransmit_request",
"dns.retransmit_request_in",
"dns.retransmit_response",
"dns.retransmit_response_in",
"dns.soa.expire_limit",
"dns.soa.minimum_ttl",
"dns.soa.refresh_interval",
"dns.soa.retry_interval",
"dns.soa.serial_number",
"dns.unsolicited",
"eapol.keydes.key_iv",
"eapol.keydes.key_len",
"eapol.keydes.replay_counter",
"eapol.keydes.type",
"eapol.len",
"eapol.type",
"eapol.version",
"eth.dst.ig",
"eth.dst.lg",
"eth.dst.oui",
"eth.fcs.status",
"eth.len",
"eth.padding",
"eth.padding_bad",
"eth.src.ig",
"eth.src.lg",
"eth.src.oui",
"http.chat",
"http.content_length",
"http.content_length_header",
"http.notification",
"http.prev_request_in",
"http.prev_response_in",
"http.request",
"http.request_in",
"http.request_number",
"http.response",
"http.response.code",
"http.response_number",
"icmp.checksum.status",
"icmp.code",
"icmp.ident",
"icmp.ident_le",
"icmp.resp_to",
"icmp.seq",
"icmp.seq_le",
"icmp.type",
"icmp.unused",
"icmpv6.checksum.status",
"icmpv6.code",
"icmpv6.mldr.nb_mcast_records",
"icmpv6.opt",
"icmpv6.opt.length",
"icmpv6.opt.type",
"icmpv6.reserved",
"icmpv6.type",
"igmp.checksum.status",
"igmp.max_resp",
"igmp.num_grp_recs",
"igmp.version",
"ip.bogus_ip_length",
"ip.len",
"ip.opt.len",
"ip.opt.ra",
"ip.opt.type",
"ip.opt.type.class",
"ip.opt.type.copy",
"ip.opt.type.number",
"ipv6.hlim",
"ipv6.hopopts.nxt",
"ipv6.nxt",
"ipv6.opt.router_alert",
"ipv6.plen",
"ipv6.tclass.dscp",
"ipv6.tclass.ecn",
"ipv6.version",
"ntp.flags.li",
"ntp.flags.mode",
"ntp.flags.vn",
"ntp.ppoll",
"ntp.precision",
"ntp.rootdelay",
"ntp.rootdispersion",
"ntp.stratum",
"stun.att.crc32.status",
"stun.att.error",
"stun.att.error.class",
"stun.att.lifetime",
"stun.attributes",
"stun.length",
"stun.network_version",
"stun.response-to",
"tcp.analysis",
"tcp.analysis.ack_lost_segment",
"tcp.analysis.acks_frame",
"tcp.analysis.bytes_in_flight",
"tcp.analysis.duplicate_ack_frame",
"tcp.analysis.duplicate_ack_num",
"tcp.analysis.flags",
"tcp.analysis.keep_alive",
"tcp.analysis.keep_alive_ack",
"tcp.analysis.lost_segment",
"tcp.analysis.out_of_order",
"tcp.analysis.push_bytes_sent",
"tcp.analysis.retransmission",
"tcp.analysis.reused_ports",
"tcp.analysis.rto_frame",
"tcp.analysis.spurious_retransmission",
"tcp.analysis.window_update",
"tcp.checksum.status",
"tcp.completeness",
"tcp.connection.fin",
"tcp.connection.fin_active",
"tcp.connection.fin_passive",
"tcp.connection.rst",
"tcp.connection.syn",
"tcp.connection.synack",
"tcp.dstport",
"tcp.fin_retransmission",
"tcp.flags.ack",
"tcp.flags.ae",
"tcp.flags.cwr",
"tcp.flags.ece",
"tcp.flags.fin",
"tcp.flags.push",
"tcp.flags.res",
"tcp.flags.reset",
"tcp.flags.syn",
"tcp.flags.urg",
"tcp.hdr_len",
"tcp.len",
"tcp.options.mss_val",
"tcp.options.sack.count",
"tcp.options.sack.dsack",
"tcp.options.sack.dsack_le",
"tcp.options.sack.dsack_re",
"tcp.options.sack_le",
"tcp.options.sack_perm",
"tcp.options.sack_re",
"tcp.options.wscale.multiplier",
"tcp.options.wscale.shift",
"tcp.pdu.size",
"tcp.reassembled.length",
"tcp.segment.count",
"tcp.segment.overlap",
"tcp.segments",
"tcp.srcport",
"tcp.stream",
"tcp.urgent_pointer",
"tcp.window_size",
"tcp.window_size_scalefactor",
"tcp.window_size_value",
"tls.alert_message",
"tls.change_cipher_spec",
"tls.handshake.certificates",
"tls.handshake.certificates_length",
"tls.handshake.challenge",
"tls.handshake.challenge_length",
"tls.handshake.cipher_spec_len",
"tls.handshake.cipher_suites_length",
"tls.handshake.ciphersuites",
"tls.handshake.client_point_len",
"tls.handshake.comp_method",
"tls.handshake.comp_methods",
"tls.handshake.comp_methods_length",
"tls.handshake.epms_len",
"tls.handshake.extension.heartbeat.mode",
"tls.handshake.extensions_ec_point_formats",
"tls.handshake.extensions_ec_point_formats_length",
"tls.handshake.extensions_length",
"tls.handshake.extensions_reneg_info_len",
"tls.handshake.extensions_server_name_len",
"tls.handshake.extensions_server_name_list_len",
"tls.handshake.extensions_server_name_type",
"tls.handshake.extensions_supported_groups",
"tls.handshake.extensions_supported_groups_length",
"tls.handshake.g_len",
"tls.handshake.p_len",
"tls.handshake.server_point_len",
"tls.handshake.session_id_length",
"tls.handshake.session_ticket_length",
"tls.handshake.session_ticket_lifetime_hint",
"tls.handshake.sig_hash_alg_len",
"tls.handshake.sig_hash_algs",
"tls.handshake.sig_len",
"tls.handshake.yc_len",
"tls.handshake.ys_len",
"tls.resumed",
"tls.sct.scts_length",
"udp.checksum.status",
"udp.dstport",
"udp.length",
"udp.length.bad",
"udp.possible_traceroute",
"udp.srcport",
"udp.stream",
"eth.dst",
"eth.src",
"ipv6.dst",
"ipv6.src",
"_ws.col.Destination",
"_ws.col.Source",
#"http.user_agent",
"udp.payload",
"stun.cookie",
"stun.id",
"stun.value",
"tcp.options",
"tcp.options.mss",
"tcp.options.sack",
"tcp.options.wscale",
"ntp.refid",
"stun.att.username",
"arp.proto.type",
"dhcp.flags",
"dhcp.flags.reserved",
"dhcp.id",
"dns.flags",
"dns.id",
"eth.fcs",
"eth.type",
"icmp.checksum",
"icmpv6.checksum",
"igmp.checksum",
"igmp.type",
"ip.id",
"ipv6.flow",
"ipv6.tclass",
"ntp.flags",
"stun.att.crc32",
"stun.att.transp",
"stun.type",
"stun.type.class",
"stun.type.method",
"stun.type.method-assignment",
"tcp.checksum",
"tcp.flags",
"tls.handshake.server_curve_type",
"tls.handshake.server_named_curve",
"tls.handshake.version",
"udp.checksum",
"http.connection",
"http.request.method",
"http.request.uri.path",
"http.response.code.desc",
"http.response.phrase",
"dns.srv.proto",
"tcp.flags.str",
"tcp.payload",
"_ws.col.Protocol",
"tls.handshake.sig_hash_alg",
"dhcp.hw.type",
"ip.dsfield",
"ip.flags",
"ipv6.opt.type",
"ipv6.opt.type.rest",
"stun.att.family",
"stun.att.ipv4-xord",
"stun.att.port-xord",
"tcp.segment",
"arp.duplicate-address-detected",
"arp.duplicate-address-frame",
"dns.srv.port",
"dns.srv.priority",
"dns.srv.weight",
"eth.addr.oui",
"eth.ig",
"eth.lg",
"ip.checksum.status",
"ip.dsfield.dscp",
"ip.dsfield.ecn",
"ip.flags.df",
"ip.flags.mf",
"ip.flags.rb",
"ip.frag_offset",
"ip.hdr_len",
"ip.proto",
"ip.ttl",
"ip.version",
"ipv6.opt",
"ipv6.opt.length",
"ipv6.opt.type.action",
"ipv6.opt.type.change",
"stun.att.padding",
"stun.att.port",
"stun.att.reserved",
"tcp.analysis.duplicate_ack",
"tcp.port",
"tls.record.length",
"udp.port",
"ip.dst",
"ip.src",
"ip.src_host",
"stun.att.ipv4",
"dhcp.hw.mac_addr"]


In [6]:
name="nihai.csv"

df=pd.read_csv(name,sep="|")
df = df[selected_cols]


In [7]:
df.values[0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [8]:
def shannon(hex_string):
    LOG_BASE = 2
   # We determine the frequency of each byte
   # in the dataset and if this frequency is not null we use it for the
   # entropy calculation.
    try:
        binary_data = bytes.fromhex(hex_string)
        dataSize = len(binary_data)
        ent = 0.0
        freq={} 
        for c in binary_data:
            if c in freq:
                freq[c] += 1
            else:
                freq[c] = 1
       # to determine if each possible value of a byte is in the list
        for key in freq.keys():
            f = float(freq[key])/dataSize
            if f > 0: # to avoid an error for log(0)
                ent = ent + f * math.log(f, LOG_BASE)
    except:
        return hex_string
    return -ent

In [9]:
def port_class(port):
    port_list=[0,53,67,68,80,123,443,1900,5353,49153]# private port list (0-Reserved,53-DNS, 67-BOOTP server, 68-BOOTP client...)
    if port in port_list: #Is the port number in the list?
        return port_list.index(port)+1 # return the port's index number in the list (actually with index+1)
    elif 0 <= port <= 1023: # return 11 if the port number is in the range 0 :1023
        return 11
    elif  1024 <= port <= 49151 : # return 12 if the port number is in the range 1024:49151
        return 12
    elif 49152 <=port <= 65535 :# return 13 if the port number is in the range 49152:65535
        return 13
    else:# return 0 if no previous conditions are met
        return 0
    

In [10]:
def comma_cleaner(val):
    clean=[]
    for v in val:
        if "," in str(v):
            temp=v.split(",")
            temp=temp[0]
        else:
            temp=v
        clean.append(temp)  
    return clean


In [11]:
def hex2dec(val):
    clean=[]
    for v in val:
        try:
            clean.append(int(v, 16))
        except:
            clean.append(v)  
    return clean


In [12]:
for d in dubs:
    temp=df[d].values
    temp=comma_cleaner(temp)
    df[d]=temp

In [13]:
df.values[0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [14]:
for h in hexvalues:
    temp=df[h].values
    temp=hex2dec(temp)
    df[h]=temp



In [15]:
df['tcp.options']=df['tcp.options'].astype(np.float32)
df['tcp.options']=df['tcp.options'].replace([np.inf, -np.inf], np.iinfo(np.uint32).max)  



In [16]:
str_cols=["http.connection",
"http.request.method",
"http.request.uri.path",
"http.response.code.desc",
"http.response.phrase",
"dns.srv.proto",
"tcp.flags.str",
"_ws.col.Protocol"]

In [17]:
for i in str_cols:
    temp=i.replace(".","_")
    val=df[i]
    val=val.replace(strs[temp])
    temp=hex2dec(temp)
    df[i]=val
df.values[0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [18]:
# Sütunları birleştir
df['Payload_Entropy'] = df["udp.payload"].combine_first(df["tcp.payload"])
del df["udp.payload"]
del df["tcp.payload"]
df.values[0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [19]:
temp=[]
for i in tqdm(df['Payload_Entropy'].values):
    temp.append(shannon(i))
df['Payload_Entropy']=temp
df.values[0]

100%|███████████████████████████████████████████████████████████████████████| 197763/197763 [00:11<00:00, 17929.77it/s]


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [20]:
df.values[0]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [21]:
df['dstport'] = df['udp.dstport'].combine_first(df['udp.dstport'])
df['srcport'] = df['udp.srcport'].combine_first(df['udp.srcport'])

temp=[]
for i in tqdm(df['dstport'].values):
    temp.append(port_class(i))
df['dstport_class']=temp

temp=[]
for i in tqdm(df['srcport'].values):
    temp.append(port_class(i))
df['srcport_class']=temp
df.values[0]

100%|██████████████████████████████████████████████████████████████████████| 197763/197763 [00:00<00:00, 716603.74it/s]


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 0.0, 16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0,
       11584852, nan, nan, nan, nan, 0, 0, 2667197, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,

In [22]:
df['dstport'] = df['udp.dstport'].combine_first(df['udp.dstport'])
df['srcport'] = df['udp.srcport'].combine_first(df['udp.srcport'])
df['ip.dst'] = df['ip.dst'].combine_first(df['ipv6.dst'])
df['ip.src'] = df['ip.src'].combine_first(df['ipv6.src'])

df['ip.bogus_ip_length'] = df['ip.bogus_ip_length'].combine_first(df['ipv6.hlim'])
df['ip.len'] = df['ip.len'].combine_first(df['ipv6.hopopts.nxt'])
df['ip.opt.len'] = df['ip.opt.len'].combine_first(df['ipv6.nxt'])
df['ip.opt.ra'] = df['ip.opt.ra'].combine_first(df['ipv6.opt.router_alert'])
df['ip.opt.type'] = df['ip.opt.type'].combine_first(df['ipv6.plen'])
df['ip.opt.type.class'] = df['ip.opt.type.class'].combine_first(df['ipv6.tclass.dscp'])
df['ip.opt.type.copy'] = df['ip.opt.type.copy'].combine_first(df['ipv6.tclass.ecn'])
df['ip.opt.type.number'] = df['ip.opt.type.number'].combine_first(df['ipv6.version'])

del df['ipv6.dst']
del df['ipv6.src']
del df['ipv6.hlim']
del df['ipv6.hopopts.nxt']
del df['ipv6.nxt']
del df['ipv6.opt.router_alert']
del df['ipv6.plen']
del df['ipv6.tclass.dscp']
del df['ipv6.tclass.ecn']
del df['ipv6.version']

In [23]:
df=df.fillna(-9999)
df.values[0]

array([-9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, 0.0,
       16.0, 1.0, 2.0, 95.0, 3.0, 2.0, 0, 0, 11584852, -9999.0, -9999.0,
       -9999.0, -9999.0, 0, 0, 2667197, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0, -9999.0,
       -9999.0, -

In [24]:
len(df.values[0])

347

In [25]:
df.to_csv("selected.csv",index=False)

In [26]:
import random
label = []
for i in range(0,len(df)):
    n = random.randint(0,1)
    label.append(n)
print(len(label))


197763


In [27]:
df["Label"]=label
df.to_csv("ML.csv",index=False)